/**
 * QVAC SDK Worker Entry (auto-generated)
 * Generated by: @qvac/sdk/commands bundleSdk
 * Plugins: 3
 *
*   - @qvac/sdk/whispercpp-transcription/plugin
*   - @qvac/sdk/tts-ggml/plugin
*   - @qvac/sdk/nmtcpp-translation/plugin
 */

import { initializeWorker, ensureRPCSetup } from "@qvac/sdk/worker-lifecycle";
import { registerPlugin } from "@qvac/sdk/plugins";
import { getServerLogger } from "@qvac/sdk/logging";

import { whisperPlugin } from "@qvac/sdk/whispercpp-transcription/plugin";
import { ttsPlugin } from "@qvac/sdk/tts-ggml/plugin";
import { nmtPlugin } from "@qvac/sdk/nmtcpp-translation/plugin";

const { hasRPCConfig } = initializeWorker();

const logger = getServerLogger();
logger.info("🐻 QVAC Worker (custom bundle)");
logger.info("📦 Plugins: 3");

registerPlugin(whisperPlugin);
registerPlugin(ttsPlugin);
registerPlugin(nmtPlugin);

// Auto-setup RPC if config present
if (hasRPCConfig) {
  ensureRPCSetup();
}
